@echo off
echo. >clean.txt
copy clean.txt a.txt
copy clean.txt ab.txt
copy clean.txt ac.txt
copy clean.txt ad.txt
copy clean.txt ae.txt
copy clean.txt b.txt
copy clean.txt bb.txt
copy clean.txt bc.txt
copy clean.txt bd.txt
copy clean.txt be.txt
copy clean.txt c.txt
copy clean.txt cb.txt
copy clean.txt ck.txt
copy clean.txt cw.txt
copy clean.txt d.txt
copy clean.txt db.txt
copy clean.txt dc.txt
copy clean.txt dd.txt
copy clean.txt de.txt
copy clean.txt e.txt
copy clean.txt eb.txt
copy clean.txt ec.txt
copy clean.txt ed.txt
copy clean.txt ee.txt
copy clean.txt f.txt
copy clean.txt fb.txt
copy clean.txt fc.txt
copy clean.txt fd.txt
copy clean.txt fe.txt
copy clean.txt g.txt
copy clean.txt gb.txt
copy clean.txt gc.txt
copy clean.txt gd.txt
copy clean.txt ge.txt
copy clean.txt h.txt
copy clean.txt hb.txt
copy clean.txt hc.txt
copy clean.txt hd.txt
copy clean.txt he.txt
copy clean.txt i.txt
copy clean.txt ib.txt
copy clean.txt ic.txt
copy clean.txt id.txt
copy clean.txt ie.txt
copy clean.txt j.txt
copy clean.txt jb.txt
copy clean.txt jc.txt
copy clean.txt jd.txt
copy clean.txt je.txt
copy clean.txt sc.txt
copy clean.txt ss.txt
copy clean.txt Pkss.txt
copy clean.txt cc.txt
copy clean.txt cd.txt
copy clean.txt ce.txt